### ISSUE TITLE
"runtime error: invalid memory address or nil pointer dereference" on tags/autoComplete/tags request,  graphite-clickhouse v 0.11.6

### ISSUE THREAD

**Issue by ifireice** [lomik/graphite-clickhouse#51]
Hi.

I have installed new version 0.11.6 and now I have a problem with autoComplete/tag

I try to request all tags in Grafana (dropdow in interface) and there is no tags. It is calling tags/autoComplete/tags

I see in carbonapi logs
```ERROR	zipper	error fetching result	{"type": "protoV2Group", "name": "clickhouse-cluster", "type": "tagName", "function": "HttpQuery.doRequest", "server": "http://graphite-clickhouse:9090", "name": "clickhouse-cluster", "uri": "http://graphite-clickhouse:9090/tags/autoComplete/tags", "error": "Get http://graphite-clickhouse:9090/tags/autoComplete/tags: EOF"}```

I see in logs graphite-clickhouse next message
```[2019-07-15T05:09:15.686Z] INFO [query] query {"query": "SELECT Path FROM graphite_tree WHERE Level=1 GROUP BY Path", "request_id": "744edfcb576e13af8d578e289f0fc50c", "time": 0.004898256}
[2019-07-15T05:09:15.687Z] INFO access {"request_id": "744edfcb576e13af8d578e289f0fc50c", "grafana": "Org:6; Dashboard:; Panel:", "time": 0.006001445, "method": "GET", "url": "/metrics/find/?format=protobuf&query=%2A", "peer": "10.0.0.29:40438", "status": 200}
2019/07/15 05:09:15 http: panic serving 10.0.0.29:40438: runtime error: invalid memory address or nil pointer dereference
goroutine 1003 [running]:
net/http.(*conn).serve.func1(0xc0003de3c0)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x16bbd60, 0x2cac7c0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/lomik/graphite-clickhouse/pkg/where.(*Where).And(0x0, 0xc0007bc400, 0x14)
	/go/src/github.com/lomik/graphite-clickhouse/_vendor/src/github.com/lomik/graphite-clickhouse/pkg/where/where.go:126 +0x37
github.com/lomik/graphite-clickhouse/pkg/where.(*Where).Andf(0x0, 0x18aa925, 0xc, 0xc000a63870, 0x1, 0x1)
	/go/src/github.com/lomik/graphite-clickhouse/_vendor/src/github.com/lomik/graphite-clickhouse/pkg/where/where.go:145 +0x75
github.com/lomik/graphite-clickhouse/autocomplete.(*Handler).ServeTags(0xc0007bb990, 0x1d4fce0, 0xc00050a820, 0xc000742100)
	/go/src/github.com/lomik/graphite-clickhouse/_vendor/src/github.com/lomik/graphite-clickhouse/autocomplete/autocomplete.go:118 +0x267
github.com/lomik/graphite-clickhouse/autocomplete.(*Handler).ServeHTTP(0xc0007bb990, 0x1d4fce0, 0xc00050a820, 0xc000742100)
	/go/src/github.com/lomik/graphite-clickhouse/_vendor/src/github.com/lomik/graphite-clickhouse/autocomplete/autocomplete.go:45 +0x80
main.Handler.func1(0x1d50020, 0xc0004a41c0, 0xc000742000)
	/go/src/github.com/lomik/graphite-clickhouse/_vendor/src/github.com/lomik/graphite-clickhouse/graphite-clickhouse.go:65 +0xe4
net/http.HandlerFunc.ServeHTTP(0xc00000f3a0, 0x1d50020, 0xc0004a41c0, 0xc000742000)
	/usr/local/go/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0x2cd1720, 0x1d50020, 0xc0004a41c0, 0xc000742000)
	/usr/local/go/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc00047d520, 0x1d50020, 0xc0004a41c0, 0xc000742000)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc0003de3c0, 0x1d5b1a0, 0xc000702700)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
```

If is getting request with defined tags all works correctly.  Example, request `seriesByTag('service_name=tech_consul_node', 'host=tech-node3', 'cpu=cpu-total')`

**Comment by lomik** [comment]
Fixed in 0.11.7

**Comment by ifireice** [comment]
Now it works. Thank you :)

**Comment by ifireice** [comment]
And thanks for fixing  https://github.com/go-graphite/carbonapi/issues/402
