### ISSUE TITLE
backtraces in graphite-web

### ISSUE THREAD

**Issue by bzed** [lomik/graphite-clickhouse#8]
Looking at the format=json outfor for a recently added metric, I see
```
[{"target": "collectd.........", "datapoints": [[null, 1492522390], [null, 1492522400], [null, 1492522410], [null, 1492522420], [null, 1492522430], [null, 1492522440], [null, 1492522450], [null, 1492522460], [null, 1492522470], [null, 1492522480], [null, 1492522490], [null, 1492522500], [null, 1492522510], [null, 1492522520], [null, 1492522530], [null, 1492522540], [null, 1492522550], [null, 1492522560], [null, 1492522570], [null, 1492522580], [null, 1492522590], [null, 1492522600], [null, 1492522610], [null, 1492522620], [null, 1492522630], [null, 1492522640], [null, 1492522650], [null, 1492522660],
........,
[NaN, 1492606510], [0.0, 1492606520], [0.0, 1492606530], [0.0, 1492606540], [0.0, 1492606550], [0.0, 1492606560], [0.0, 1492606570], [0.0, 1492606580], [0.0, 1492606590], [0.0, 1492606600], [0.0, 1492606610], [0.0, 1492606620], [0.0, 1492606630], [0.0, 1492606640], [0.0, 1492606650], [0.0, 1492606660], [0.0, 1492606670], [0.0, 1492606680], [0.0, 1492606690], [0.0, 1492606700], [0.0, 1492606710], [0.0, 1492606720], [0.0, 1492606730], [0.0, 1492606740], [0.0, 1492606750], [0.0, 1492606760], [0.0, 1492606770], [0.0, 1492606780], [0.0, 1492606790], [0.0, 1492606800], [0.0, 1492606810], [0.0, 1492606820], [0.0, 1492606830], [0.0, 1492606840], [0.0, 1492606850], [0.0, 1492606860], [0.0, 1492606870], [0.0, 1492606880], [0.0, 1492606890], [0.0, 1492606900], [0.0, 1492606910], [0.0, 1492606920], [0.0, 1492606930], [0.0, 1492606940], [0.0, 1492606950], [0.0, 1492606960], [0.0, 1492606970], [0.0, 1492606980], [0.0, 1492606990], [0.0, 1492607000], [0.0, 1492607010], [0.0, 1492607020], [0.0, 1492607030], [0.0, 1492607040], [0.0, 1492607050], [0.0, 1492607060], [0.0, 1492607070], [0.0, 1492607080], [0.0, 1492607090], [0.0, 1492607100], [0.0, 1492607110], [0.0, 1492607120], [0.0, 1492607130], [0.0, 1492607140], [0.0, 1492607150], [0.0, 1492607160], [0.0, 1492607170], [0.0, 1492607180], [0.0, 1492607190], [0.0, 1492607200], [0.0, 1492607210], [0.0, 1492607220], [0.0, 1492607230], [0.0, 1492607240], [0.0, 1492607250], [0.0, 1492607260], [0.0, 1492607270], [0.0, 1492607280], [0.0, 1492607290], [0.0, 1492607300], [0.0, 1492607310], [0.0, 1492607320], [0.0, 1492607330], [0.0, 1492607340], [0.0, 1492607350], [0.0, 1492607360], [0.0, 1492607370], [0.0, 1492607380], [0.0, 1492607390], [0.0, 1492607400], [0.0, 1492607410], [0.0, 1492607420], [0.0, 1492607430], [0.0, 1492607440], [0.0, 1492607450], [0.0, 1492607460], [0.0, 1492607470], [0.0, 1492607480], [0.0, 1492607490], [0.0, 1492607500], [0.0, 1492607510], [0.0, 1492607520], [0.0, 1492607530], [0.0, 1492607540], [0.0, 1492607550], [0.0, 1492607560], [0.0, 1492607570], [0.0, 1492607580], [0.0, 1492607590], [0.0, 1492607600], [0.0, 1492607610], [0.0, 1492607620], [0.0, 1492607630], [0.0, 1492607640], [0.0, 1492607650], [0.0, 1492607660], [0.0, 1492607670], [0.0, 1492607680], [0.0, 1492607690], [0.0, 1492607700], [0.0, 1492607710], [0.0, 1492607720], [0.0, 1492607730], [0.0, 1492607740], [0.0, 1492607750], [0.0, 1492607760], [0.0, 1492607770], [0.0, 1492607780], [0.0, 1492607790], [0.0, 1492607800], [0.0, 1492607810], [0.0, 1492607820], [0.0, 1492607830], [0.0, 1492607840], [0.0, 1492607850], [0.0, 1492607860], [0.0, 1492607870], [0.0, 1492607880], [0.0, 1492607890], [0.0, 1492607900], [0.0, 1492607910], [0.0, 1492607920], [0.0, 1492607930], [0.0, 1492607940], [0.0, 1492607950], [0.0, 1492607960], [0.0, 1492607970], [0.0, 1492607980], [0.0, 1492607990], [0.0, 1492608000], [0.0, 1492608010], [0.0, 1492608020], [0.0, 1492608030], [0.0, 1492608040], [0.0, 1492608050], [0.0, 1492608060], [0.0, 1492608070], [0.0, 1492608080], [0.0, 1492608090], [0.0, 1492608100], [0.0, 1492608110], [0.0, 1492608120], [0.0, 1492608130], [0.0, 1492608140], [0.0, 1492608150], [0.0, 1492608160], [0.0, 1492608170], [0.0, 1492608180], [0.0, 1492608190], [0.0, 1492608200], [0.0, 1492608210], [0.0, 1492608220], [0.0, 1492608230], [0.0, 1492608240], [0.0, 1492608250], [0.0, 1492608260], [0.0, 1492608270], [0.0, 1492608280], [0.0, 1492608290], [0.0, 1492608300], [0.0, 1492608310], [0.0, 1492608320], [0.0, 1492608330], [0.0, 1492608340], [0.0, 1492608350], [0.0, 1492608360], [0.0, 1492608370], [0.0, 1492608380], [0.0, 1492608390], [0.0, 1492608400], [0.0, 1492608410], [0.0, 1492608420], [0.0, 1492608430], [0.0, 1492608440], [0.0, 1492608450], [0.0, 1492608460], [0.0, 1492608470], [0.0, 1492608480], [0.0, 1492608490], [0.0, 1492608500], [0.0, 1492608510], [0.0, 1492608520], [0.0, 1492608530], [0.0, 1492608540], [0.0, 1492608550], [0.0, 1492608560], [0.0, 1492608570], [0.0, 1492608580], [0.0, 1492608590], [0.0, 1492608600], [0.0, 1492608610], [0.0, 1492608620], [0.0, 1492608630], [0.0, 1492608640], [0.0, 1492608650], [0.0, 1492608660], [0.0, 1492608670], [0.0, 1492608680], [0.0, 1492608690], [0.0, 1492608700], [0.0, 1492608710], [0.0, 1492608720], [0.0, 1492608730], [0.0, 1492608740], [0.0, 1492608750], [0.0, 1492608760], [0.0, 1492608770], [null, 1492608780]]}]

```

Trying to look at the format=png image of such a query results in the following backtrace:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.7/dist-packages/graphite/render/views.py", line 215, in renderView
    image = doImageRender(requestOptions['graphClass'], graphOptions)
  File "/usr/lib/python2.7/dist-packages/graphite/render/views.py", line 436, in doImageRender
    img = graphClass(**graphOptions)
  File "/usr/lib/python2.7/dist-packages/graphite/render/glyph.py", line 196, in __init__
    self.drawGraph(**params)
  File "/usr/lib/python2.7/dist-packages/graphite/render/glyph.py", line 678, in drawGraph
    self.setupYAxis()
  File "/usr/lib/python2.7/dist-packages/graphite/render/glyph.py", line 1137, in setupYAxis
    self.yLabelWidth = max([self.getExtents(label)['width'] for label in self.yLabels])
ValueError: max() arg is an empty sequence

```

Right now I have no idea where this issue comes from, it might be the NaN value. With the normal graphite whisper backend the issue does not happen at all.

**Comment by lomik** [comment]
Could you show original data from clickhouse?

**Comment by bzed** [comment]
```
SELECT 
    'collectd....', 
    Time, 
    Value, 
    Timestamp
FROM graphite 
WHERE (Path IN 'collectd................value') AND ((Date >= '2017-04-18') AND (Date <= '2017-04-19') AND (Time >= 1492522309) AND (Time <= 1492608709))

┌─\'collectd....\'─┬───────Time─┬─Value─┬──Timestamp─┐
│ collectd....     │ 1492606510 │   nan │ 1492606519 │
│ collectd....     │ 1492606520 │     0 │ 1492606529 │
│ collectd....     │ 1492606530 │     0 │ 1492606539 │
│ collectd....     │ 1492606540 │     0 │ 1492606549 │
│ collectd....     │ 1492606550 │     0 │ 1492606559 │
│ collectd....     │ 1492606560 │     0 │ 1492606569 │
│ collectd....     │ 1492606570 │     0 │ 1492606579 │
│ collectd....     │ 1492606580 │     0 │ 1492606588 │
│ collectd....     │ 1492606590 │     0 │ 1492606599 │
│ collectd....     │ 1492606600 │     0 │ 1492606609 │
│ collectd....     │ 1492606610 │     0 │ 1492606619 │
│ collectd....     │ 1492606620 │     0 │ 1492606629 │
│ collectd....     │ 1492606630 │     0 │ 1492606639 │
│ collectd....     │ 1492606640 │     0 │ 1492606649 │
│ collectd....     │ 1492606650 │     0 │ 1492606659 │
│ collectd....     │ 1492606660 │     0 │ 1492606668 │
│ collectd....     │ 1492606670 │     0 │ 1492606678 │
│ collectd....     │ 1492606680 │     0 │ 1492606689 │
│ collectd....     │ 1492606690 │     0 │ 1492606699 │
│ collectd....     │ 1492606700 │     0 │ 1492606709 │
│ collectd....     │ 1492606710 │     0 │ 1492606719 │
│ collectd....     │ 1492606720 │     0 │ 1492606729 │
│ collectd....     │ 1492606730 │     0 │ 1492606739 │
│ collectd....     │ 1492606740 │     0 │ 1492606749 │
│ collectd....     │ 1492606750 │     0 │ 1492606759 │
│ collectd....     │ 1492606760 │     0 │ 1492606769 │
│ collectd....     │ 1492606770 │     0 │ 1492606779 │
│ collectd....     │ 1492606780 │     0 │ 1492606789 │
│ collectd....     │ 1492606790 │     0 │ 1492606799 │
│ collectd....     │ 1492606800 │     0 │ 1492606809 │
│ collectd....     │ 1492606810 │     0 │ 1492606819 │
│ collectd....     │ 1492606820 │     0 │ 1492606829 │
│ collectd....     │ 1492606830 │     0 │ 1492606839 │
│ collectd....     │ 1492606840 │     0 │ 1492606849 │
│ collectd....     │ 1492606850 │     0 │ 1492606858 │
│ collectd....     │ 1492606860 │     0 │ 1492606869 │
│ collectd....     │ 1492606870 │     0 │ 1492606879 │
│ collectd....     │ 1492606880 │     0 │ 1492606889 │
│ collectd....     │ 1492606890 │     0 │ 1492606894 │
│ collectd....     │ 1492606900 │     0 │ 1492606902 │
│ collectd....     │ 1492606910 │     0 │ 1492606912 │
│ collectd....     │ 1492606920 │     0 │ 1492606922 │
│ collectd....     │ 1492606930 │     0 │ 1492606932 │
│ collectd....     │ 1492606940 │     0 │ 1492606942 │
│ collectd....     │ 1492606950 │     0 │ 1492606952 │
│ collectd....     │ 1492606960 │     0 │ 1492606962 │
│ collectd....     │ 1492606970 │     0 │ 1492606972 │
│ collectd....     │ 1492606980 │     0 │ 1492606982 │
│ collectd....     │ 1492606990 │     0 │ 1492606992 │
│ collectd....     │ 1492607000 │     0 │ 1492607002 │
│ collectd....     │ 1492607010 │     0 │ 1492607012 │
│ collectd....     │ 1492607020 │     0 │ 1492607022 │
│ collectd....     │ 1492607030 │     0 │ 1492607032 │
│ collectd....     │ 1492607040 │     0 │ 1492607042 │
│ collectd....     │ 1492607050 │     0 │ 1492607052 │
│ collectd....     │ 1492607060 │     0 │ 1492607062 │
│ collectd....     │ 1492607070 │     0 │ 1492607072 │
│ collectd....     │ 1492607080 │     0 │ 1492607082 │
│ collectd....     │ 1492607090 │     0 │ 1492607092 │
│ collectd....     │ 1492607100 │     0 │ 1492607102 │
│ collectd....     │ 1492607110 │     0 │ 1492607112 │
│ collectd....     │ 1492607120 │     0 │ 1492607122 │
│ collectd....     │ 1492607130 │     0 │ 1492607132 │
│ collectd....     │ 1492607140 │     0 │ 1492607142 │
│ collectd....     │ 1492607150 │     0 │ 1492607152 │
│ collectd....     │ 1492607160 │     0 │ 1492607162 │
│ collectd....     │ 1492607170 │     0 │ 1492607172 │
│ collectd....     │ 1492607180 │     0 │ 1492607182 │
│ collectd....     │ 1492607190 │     0 │ 1492607192 │
│ collectd....     │ 1492607200 │     0 │ 1492607202 │
│ collectd....     │ 1492607210 │     0 │ 1492607212 │
│ collectd....     │ 1492607220 │     0 │ 1492607222 │
│ collectd....     │ 1492607230 │     0 │ 1492607232 │
│ collectd....     │ 1492607240 │     0 │ 1492607242 │
│ collectd....     │ 1492607250 │     0 │ 1492607252 │
│ collectd....     │ 1492607260 │     0 │ 1492607262 │
│ collectd....     │ 1492607270 │     0 │ 1492607272 │
│ collectd....     │ 1492607280 │     0 │ 1492607282 │
│ collectd....     │ 1492607290 │     0 │ 1492607292 │
│ collectd....     │ 1492607300 │     0 │ 1492607302 │
│ collectd....     │ 1492607310 │     0 │ 1492607312 │
│ collectd....     │ 1492607320 │     0 │ 1492607322 │
│ collectd....     │ 1492607330 │     0 │ 1492607332 │
│ collectd....     │ 1492607340 │     0 │ 1492607342 │
│ collectd....     │ 1492607350 │     0 │ 1492607352 │
│ collectd....     │ 1492607360 │     0 │ 1492607362 │
│ collectd....     │ 1492607370 │     0 │ 1492607372 │
│ collectd....     │ 1492607380 │     0 │ 1492607382 │
│ collectd....     │ 1492607390 │     0 │ 1492607392 │
│ collectd....     │ 1492607400 │     0 │ 1492607402 │
│ collectd....     │ 1492607410 │     0 │ 1492607412 │
│ collectd....     │ 1492607420 │     0 │ 1492607422 │
│ collectd....     │ 1492607430 │     0 │ 1492607432 │
│ collectd....     │ 1492607440 │     0 │ 1492607442 │
│ collectd....     │ 1492607450 │     0 │ 1492607452 │
│ collectd....     │ 1492607460 │     0 │ 1492607462 │
│ collectd....     │ 1492607470 │     0 │ 1492607472 │
└──────────────────┴────────────┴───────┴────────────┘
┌─\'collectd....\'─┬───────Time─┬─Value─┬──Timestamp─┐
│ collectd....     │ 1492607480 │     0 │ 1492607482 │
│ collectd....     │ 1492607490 │     0 │ 1492607492 │
│ collectd....     │ 1492607500 │     0 │ 1492607502 │
│ collectd....     │ 1492607510 │     0 │ 1492607512 │
│ collectd....     │ 1492607520 │     0 │ 1492607522 │
│ collectd....     │ 1492607530 │     0 │ 1492607532 │
│ collectd....     │ 1492607540 │     0 │ 1492607547 │
│ collectd....     │ 1492607550 │     0 │ 1492607557 │
│ collectd....     │ 1492607560 │     0 │ 1492607567 │
│ collectd....     │ 1492607570 │     0 │ 1492607577 │
│ collectd....     │ 1492607580 │     0 │ 1492607587 │
│ collectd....     │ 1492607590 │     0 │ 1492607597 │
│ collectd....     │ 1492607600 │     0 │ 1492607607 │
│ collectd....     │ 1492607610 │     0 │ 1492607617 │
│ collectd....     │ 1492607620 │     0 │ 1492607627 │
│ collectd....     │ 1492607630 │     0 │ 1492607637 │
│ collectd....     │ 1492607640 │     0 │ 1492607647 │
│ collectd....     │ 1492607650 │     0 │ 1492607657 │
│ collectd....     │ 1492607660 │     0 │ 1492607667 │
│ collectd....     │ 1492607670 │     0 │ 1492607677 │
│ collectd....     │ 1492607680 │     0 │ 1492607687 │
│ collectd....     │ 1492607690 │     0 │ 1492607697 │
│ collectd....     │ 1492607700 │     0 │ 1492607707 │
│ collectd....     │ 1492607710 │     0 │ 1492607717 │
│ collectd....     │ 1492607720 │     0 │ 1492607727 │
│ collectd....     │ 1492607730 │     0 │ 1492607737 │
│ collectd....     │ 1492607740 │     0 │ 1492607747 │
│ collectd....     │ 1492607750 │     0 │ 1492607757 │
│ collectd....     │ 1492607760 │     0 │ 1492607767 │
│ collectd....     │ 1492607770 │     0 │ 1492607777 │
│ collectd....     │ 1492607780 │     0 │ 1492607787 │
│ collectd....     │ 1492607790 │     0 │ 1492607797 │
│ collectd....     │ 1492607800 │     0 │ 1492607807 │
│ collectd....     │ 1492607810 │     0 │ 1492607817 │
│ collectd....     │ 1492607820 │     0 │ 1492607827 │
│ collectd....     │ 1492607830 │     0 │ 1492607837 │
│ collectd....     │ 1492607840 │     0 │ 1492607847 │
│ collectd....     │ 1492607850 │     0 │ 1492607857 │
│ collectd....     │ 1492607860 │     0 │ 1492607867 │
│ collectd....     │ 1492607870 │     0 │ 1492607877 │
│ collectd....     │ 1492607880 │     0 │ 1492607887 │
│ collectd....     │ 1492607890 │     0 │ 1492607897 │
│ collectd....     │ 1492607900 │     0 │ 1492607907 │
│ collectd....     │ 1492607910 │     0 │ 1492607917 │
│ collectd....     │ 1492607920 │     0 │ 1492607927 │
│ collectd....     │ 1492607930 │     0 │ 1492607937 │
│ collectd....     │ 1492607940 │     0 │ 1492607947 │
│ collectd....     │ 1492607950 │     0 │ 1492607957 │
│ collectd....     │ 1492607960 │     0 │ 1492607967 │
│ collectd....     │ 1492607970 │     0 │ 1492607977 │
│ collectd....     │ 1492607980 │     0 │ 1492607987 │
│ collectd....     │ 1492607990 │     0 │ 1492607997 │
│ collectd....     │ 1492608000 │     0 │ 1492608007 │
│ collectd....     │ 1492608010 │     0 │ 1492608017 │
│ collectd....     │ 1492608020 │     0 │ 1492608027 │
│ collectd....     │ 1492608030 │     0 │ 1492608037 │
│ collectd....     │ 1492608040 │     0 │ 1492608047 │
│ collectd....     │ 1492608050 │     0 │ 1492608057 │
│ collectd....     │ 1492608060 │     0 │ 1492608067 │
│ collectd....     │ 1492608070 │     0 │ 1492608077 │
│ collectd....     │ 1492608080 │     0 │ 1492608087 │
│ collectd....     │ 1492608090 │     0 │ 1492608097 │
│ collectd....     │ 1492608100 │     0 │ 1492608107 │
│ collectd....     │ 1492608110 │     0 │ 1492608117 │
│ collectd....     │ 1492608120 │     0 │ 1492608127 │
│ collectd....     │ 1492608130 │     0 │ 1492608137 │
│ collectd....     │ 1492608140 │     0 │ 1492608147 │
│ collectd....     │ 1492608150 │     0 │ 1492608157 │
│ collectd....     │ 1492608160 │     0 │ 1492608167 │
│ collectd....     │ 1492608170 │     0 │ 1492608177 │
│ collectd....     │ 1492608180 │     0 │ 1492608187 │
│ collectd....     │ 1492608190 │     0 │ 1492608197 │
│ collectd....     │ 1492608200 │     0 │ 1492608207 │
│ collectd....     │ 1492608210 │     0 │ 1492608217 │
│ collectd....     │ 1492608220 │     0 │ 1492608227 │
│ collectd....     │ 1492608230 │     0 │ 1492608237 │
│ collectd....     │ 1492608240 │     0 │ 1492608247 │
│ collectd....     │ 1492608250 │     0 │ 1492608257 │
│ collectd....     │ 1492608260 │     0 │ 1492608267 │
│ collectd....     │ 1492608270 │     0 │ 1492608277 │
│ collectd....     │ 1492608280 │     0 │ 1492608287 │
│ collectd....     │ 1492608290 │     0 │ 1492608297 │
│ collectd....     │ 1492608300 │     0 │ 1492608307 │
│ collectd....     │ 1492608310 │     0 │ 1492608317 │
│ collectd....     │ 1492608320 │     0 │ 1492608327 │
│ collectd....     │ 1492608330 │     0 │ 1492608337 │
│ collectd....     │ 1492608340 │     0 │ 1492608347 │
│ collectd....     │ 1492608350 │     0 │ 1492608357 │
│ collectd....     │ 1492608360 │     0 │ 1492608367 │
│ collectd....     │ 1492608370 │     0 │ 1492608377 │
│ collectd....     │ 1492608380 │     0 │ 1492608387 │
│ collectd....     │ 1492608390 │     0 │ 1492608397 │
│ collectd....     │ 1492608400 │     0 │ 1492608407 │
│ collectd....     │ 1492608410 │     0 │ 1492608417 │
│ collectd....     │ 1492608420 │     0 │ 1492608427 │
│ collectd....     │ 1492608430 │     0 │ 1492608437 │
│ collectd....     │ 1492608440 │     0 │ 1492608447 │
│ collectd....     │ 1492608450 │     0 │ 1492608457 │
│ collectd....     │ 1492608460 │     0 │ 1492608467 │
│ collectd....     │ 1492608470 │     0 │ 1492608477 │
│ collectd....     │ 1492608480 │     0 │ 1492608487 │
│ collectd....     │ 1492608490 │     0 │ 1492608497 │
│ collectd....     │ 1492608500 │     0 │ 1492608507 │
│ collectd....     │ 1492608510 │     0 │ 1492608517 │
│ collectd....     │ 1492608520 │     0 │ 1492608527 │
│ collectd....     │ 1492608530 │     0 │ 1492608537 │
│ collectd....     │ 1492608540 │     0 │ 1492608547 │
│ collectd....     │ 1492608550 │     0 │ 1492608557 │
│ collectd....     │ 1492608560 │     0 │ 1492608567 │
│ collectd....     │ 1492608570 │     0 │ 1492608577 │
│ collectd....     │ 1492608580 │     0 │ 1492608587 │
│ collectd....     │ 1492608590 │     0 │ 1492608597 │
│ collectd....     │ 1492608600 │     0 │ 1492608607 │
│ collectd....     │ 1492608610 │     0 │ 1492608617 │
│ collectd....     │ 1492608620 │     0 │ 1492608627 │
│ collectd....     │ 1492608630 │     0 │ 1492608637 │
│ collectd....     │ 1492608640 │     0 │ 1492608647 │
│ collectd....     │ 1492608650 │     0 │ 1492608657 │
│ collectd....     │ 1492608660 │     0 │ 1492608667 │
│ collectd....     │ 1492608670 │     0 │ 1492608677 │
│ collectd....     │ 1492608680 │     0 │ 1492608687 │
│ collectd....     │ 1492608690 │     0 │ 1492608697 │
│ collectd....     │ 1492608700 │     0 │ 1492608707 │
└──────────────────┴────────────┴───────┴────────────┘

220 rows in set. Elapsed: 0.018 sec. Processed 106.50 thousand rows, 11.61 MB (6.04 million rows/s., 658.42 MB/s.) 

:) 
```

**Comment by lomik** [comment]
I have check for NaN in carbon-clickhouse https://github.com/lomik/carbon-clickhouse/blob/1617c73e261e8941968c8a6227a37d8c495a643b/receiver/plain.go#L73
Apparently it did not work for some reason

I'll add validation to graphite-clickhouse too

**Comment by lomik** [comment]
But I don't have check in pickle receiver... Are you use it?

**Comment by bzed** [comment]
Yes, I've migrated 99% to pickle

**Comment by lomik** [comment]
graphite-clickhouse from master should remove NaN values

**Comment by lomik** [comment]
carbon-clickhouse from master shouldn't write NaN values into ClickHouse
